export const LOADING_SHOW = "LOADING_SHOW";
export const CHANGE_TARGET_PATH = "CHANGE_TARGET_PATH";
export const CHANGE_ACCESS_MENU = "CHANGE_ACCESS_MENU";
export const CHANGE_MODULE = "CHANGE_MODULE";